### ISSUE TITLE
Error on build when importing framework directly

### ISSUE THREAD

**Issue by davidvpe** [mopinion/mopinion-sdk-ios-web#11]
Currently when we try to archive a project in Xcode 12.4 when using the iOS Web Mopinion SDK we get the following error:

`error: Building for iOS, but the linked and embedded framework 'MopinionSDK.framework' was built for iOS + iOS Simulator.`

**Comment by davidvpe** [comment]
I read that setting validate workspace option to YES would allow the project to build (not to archive) but I still get this other issue:

`Failed to build module 'MopinionSDK' from its module interface; the compiler that produced it, 'Apple Swift version 5.2 (swiftlang-1103.0.32.1 clang-1103.0.32.29)', may have used features that aren't supported by this compiler, 'Apple Swift version 5.3.2 (swiftlang-1200.0.45 clang-1200.0.32.28)`

**Comment by davidvpe** [comment]
Is this repo still supported?

**Comment by Piethot** [comment]
Hi David, sorry for the late reply. We will look into the issue you encountered and get back to you as soon as possible.

**Comment by Piethot** [comment]
Hi David,

our current mopinion-sdk-ios-web 0.4.6 does build and archive a project fine using Xcode 12.4. We tested on both macOS Catalina on Intel, and macOS Big Sur on Apple Silicon.
Yet, Xcode may give these warnings for several reasons. Our SDK is a multi-architecture (fat) framework. To archive a project, the build settings for “Release” matters.

1. In Xcode, use the same build-settings for “Build active architectures only” for your project and all of your sub-projects, including the CocoaPods.
2. In Xcode, perform a “Clean build folder”.
3. Build / Make your archive for the desired architecture.
Here is an example setting used on Apple Silicon to build only arm64:
![afbeelding-20210316-154933](https://user-images.githubusercontent.com/12810425/111345593-ba537e00-867d-11eb-86d1-011bf4444170.png)
Sometimes, after a new Xcode version install, it helps to restart Xcode and open your projects again.

Could you please let us know whether these instructions helped you?

Kind regards,
Pieter

**Comment by davidvpe** [comment]
Hi @Piethot thanks for the response, we do not use Cocoapods as our dependency manager, we use SPM so for Mopinion we import it manually

**Comment by Piethot** [comment]
Hi @davidvpe,

please see our additional advice to get this up and running
”Our SDK framework includes builds for the Intel simulator, which you’ll have to exclude from your archive. So make sure the SDK is a target in your Xcode workspace in order to be able to specify build settings.

You can also make a dummy project with cocoapods to verify what the project settings should be.“
Deployment through cocoapods is advised as we are sure that this will result in a correct installation. If manual installation is your only option then please let us know. Be aware that it will then require additional time before we can update you on how to proceed with the manual installation.

Kind regards,
Pieter
