### ISSUE TITLE
Not working on Xcode 11.1

### ISSUE THREAD

**Issue by davidvpe** [mopinion/mopinion-sdk-ios-web#7]
The latest version of the SDK cannot be imported on an Xcode 11.1 project.

**Comment by stevenkuipers** [comment]
Hi David,

For Xcode 11 and higher, you need to use version 0.4.0 of the web SDK. Add [https://github.com/mopinion/mopinion-sdk-ios-web#install-cocoapods](this) to your podfile.

If you are using this version and are still unable to import the SDK, could you contact us at support@mopinion.com and provide a log of the error messages you are receiving and details on how to reproduce it. For now, I will close the issue here at Github.
